# Generated by Django 3.2.16 on 2022-11-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangeratemodel',
            constraint=models.UniqueConstraint(fields=('code', 'base'), name='unique conversion by base'),
        ),
    ]
